export * from "./download-section.interface";
export * from './url-with-text.interface';
export * from './feature.interface';
export * from './generic-text.interface';
export * from './feature-with-special-property.interface'
export * from './text-or-link.interface';
export * from './paragraph-with-links.interface';
export * from './colored-tag.interface';
export * from './special-property.interface';